### ISSUE TITLE
Add instructions to tie PRs to Tickets in Waffle without closing

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/playbook#53]
We should use waffle's "Connected to _issue-number_" syntax rather than github's "closes" syntax to associate tickets and PRs in our waffle board without closing the issue.

For additional background, link to https://help.waffle.io/faq/waffle-workflow/use-waffles-connect-keyword-to-connect-prs-to-issues

**Comment by bess** [comment]
This is addressed here: https://github.com/curationexperts/playbook/blob/master/every_project/waffle.md
