### ISSUE TITLE
Normalize labels across project waffles

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/playbook#9]
**ACCEPTANCE**
- [ ] Create a superset list of all labels in the [projects updated in the last month](https://github.com/curationexperts)
- [x] Deduplicate the set of labels, figure out what labels we should add to new projects 
- [ ] Document the list of labels we should add in the DCE playbook repository in addition to the [github defaults](https://help.github.com/articles/about-labels/#using-default-labels)

**Comment by bess** [comment]
Documented here: https://github.com/curationexperts/playbook/blob/master/every_project/waffle.md

**Comment by RachelDCE** [comment]
Labels in this board have been normalized. The only exception was Laevigata - where there is an additional column called Ready for QA.
